version: "3.9"

networks:
  app-network:
    driver: bridge


services:

  app:
    networks:
      - app-network
    build: .
    restart: always
    env_file: .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    networks:
      - app-network
    restart: always
    env_file: .env
